#!/bin/bash
#set -x
check_existing_installation() {
    if command -v docker >/dev/null || command -v podman >/dev/null && command -v docker-compose >/dev/null; then
        echo "Docker / Podman e Docker Compose já estão instalados no sistema."
        exit 0
    fi
}

check_linux_distribution() {
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        if [ "$ID" = "debian" ] || [ "$ID" = "ubuntu" ]; then
            echo "Debian ou Ubuntu detectado."
            install_docker_compose
        elif [ "$ID" = "rhel" ] || [ "$ID" = "fedora" ] ; then
            echo "RedHat, CentOS ou Fedora detectado."
            install_docker_compose
        elif [ "$ID" = "suse" ] || [ "$ID" = "sles" ]; then
            echo "SUSE detectado."
            install_docker_compose
        elif [ "$ID" = "amzn" ]; then
            echo "Amazon Linux detectado."
            install_docker_compose_amzn
        elif [ "$ID" = "ol" ]; then
            echo "Oracle Linux detectado."
            install_docker_compose_ol
        elif [ "$ID" = "centos" ] || [ "$ID" = "rhel" ]; then
            echo "CentOS 8 detectado."
            install_docker_compose_centos8
        else
            echo "Distribuição não suportada."
        fi
    else
        echo "Arquivo /etc/os-release não encontrado. Não é possível determinar a distribuição."
    fi
}

install_docker_compose() {
    echo "Instalando Docker..."
    curl -fsSL https://get.docker.com -o get-docker.sh
    sudo sh get-docker.sh
    sudo usermod -aG docker $USER
    sudo systemctl start docker
    sudo systemctl enable docker
    sudo rm -f get-docker.sh
    echo "Docker instalado com sucesso."

    echo "Instalando Docker Compose v2..."
    sudo curl -fsSL -o /usr/local/bin/docker-compose https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-linux-x86_64
    sudo chmod +x /usr/local/bin/docker-compose
    echo "Docker Compose v2 instalado com sucesso."
}

install_docker_compose_amzn() {
    echo "Instalando Docker..."
    sudo yum install docker -y
    sudo systemctl start docker
    sudo systemctl enable docker
    echo "Docker instalado com sucesso."

    echo "Instalando Docker Compose v2..."
    sudo curl -fsSL -o /usr/local/bin/docker-compose https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-linux-x86_64
    sudo chmod +x /usr/local/bin/docker-compose
    echo "Docker Compose v2 instalado com sucesso."
}

install_docker_compose_ol() {
    echo "Instalando Docker / Podman..."
    sudo yum install docker -y
    sudo systemctl start podman
    sudo systemctl enable podman
    echo "Docker / Podman instalado com sucesso."

    echo "Instalando Docker Compose v2..."
    sudo curl -fsSL -o /usr/local/bin/docker-compose https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-linux-x86_64
    sudo chmod +x /usr/local/bin/docker-compose
    echo "Docker Compose v2 instalado com sucesso."
}
install_docker_compose_centos8() {
    echo "Instalando Docker..."
    sudo yum install -y yum-utils
    sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    sudo yum erase podman buildah -y
    sudo yum install docker-ce docker-ce-cli containerd.io -y
    sudo usermod -a -G docker ${USER}
    sudo systemctl enable docker
    sudo systemctl start docker
    systemctl status docker
    echo "Docker instalado com sucesso."

    echo "Instalando Docker Compose v2..."
    sudo curl -fsSL -o /usr/local/bin/docker-compose https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-linux-x86_64
    sudo chmod +x /usr/local/bin/docker-compose
	export PATH=$PATH:/usr/local/bin/
    echo "Docker Compose v2 instalado com sucesso."
}    

check_existing_installation

check_linux_distribution