version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: elasticsearch
    restart: always
    environment:
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
      - node.name=elasticsearch
      - discovery.type=single-node
    ports:
      - "${ELASTIC_REST_PORT}:9200"
      - "${ELASTIC_NODE_PORT}:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data/
    networks:
      - stack

  logstash:
    image: docker.elastic.co/logstash/logstash:8.9.0
    container_name: logstash
    restart: always
    environment:
      - LS_JAVA_OPTS=-Xmx256m -Xms256m
    volumes:
      - ./logstash-config:/usr/share/logstash/config/
    command: logstash -f /usr/share/logstash/config/logstash.conf
    depends_on:
      - elasticsearch
    ports:
      - "${LOGSTASH_BEATS_PORT}:5000"
      - "${LOGSTASH_API_PORT}:9600"
    networks:
      - stack

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0
    container_name: kibana
    restart: always
    environment:
      - ELASTICSEARCH=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "${KIBANA_PORT}:5601"
    networks:
      - stack

volumes:
  es_data:

networks:
  stack:
    driver: bridge
